baseurl: /nextworld

auto: true
pygments: true
lsi: false

markdown: rdiscount
pygments: true

permalink: /:year/:month/:day/:title
paginate: 10
exclude:
  [".rvmrc", ".rbenv-version", "README.md", "Rakefile",
  "changelog.md"]
